### PR TITLE
Limit pickling for a selected top

### PR DESCRIPTION
**Pull request by micprog**
Adds `top_module` parameter to pickle only for a selected top module, accordingly adjusting the pickle and output manifest.
As a graph is built either way, this also allows exporting of a DOT graph of instantiated modules.

### CODE REVIEW

**Review by thommythomaso — COMMENTED** [review]
LGTM. Thinking about it, Morty could read the manifest file and reemit a modified manifest file that contains an in-order subset of required sources. Not sure if this is useful. It could be a preprocessing step for other tools that require this. Maybe support for `f` files could be a nice thing to have in this context.

**Comment by micprog** [comment]
> LGTM. Thinking about it, Morty could read the manifest file and reemit a modified manifest file that contains an in-order subset of required sources. Not sure if this is useful. It could be a preprocessing step for other tools that require this. Maybe support for `f` files could be a nice thing to have in this context.

Have you tried the `--manifest` flag?

**Comment by thommythomaso** [comment]
> 

I missed this option. This is exactly what I was looking for. Maybe the help could point out that this is subject to the `--top` option.

**Comment by thommythomaso** [comment]
I will add compatibility with `f` files as a separate feature request in this case.

**Review by thommythomaso — APPROVED** [review]

**Pull request merged**
